### ISSUE TITLE
TypeError: ('Could not adapt', u'W', ... ITextRowSchema>) when upgraded to 0.7.4

### ISSUE THREAD

**Issue by djowett** [fourdigits/collective.cookiecuttr#11]
I get this Traceback after upgrading from 0.7.1 to 0.7.4 & trying to access /@@cookiecuttr-settings

    Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module plone.z3cform.layout, line 66, in __call__
    Module plone.z3cform.layout, line 50, in update
    Module plone.z3cform.fieldsets.extensible, line 59, in update
    Module plone.z3cform.patch, line 30, in GroupForm_update
    Module z3c.form.group, line 128, in update
    Module collective.cookiecuttr.browser.controlpanel, line 16, in updateWidgets
    Module z3c.form.form, line 134, in updateWidgets
    Module z3c.form.field, line 277, in update
    Module z3c.form.browser.multi, line 63, in update
    Module z3c.form.browser.widget, line 171, in update
    Module z3c.form.widget, line 475, in update
    Module z3c.form.widget, line 131, in update
    Module z3c.form.widget, line 470, in value
    Module collective.z3cform.datagridfield.datagridfield, line 102, in updateWidgets
    Module z3c.form.widget, line 416, in updateWidgets
    Module z3c.form.widget, line 393, in applyValue
    Module collective.z3cform.datagridfield.datagridfield, line 209, in set
    Module z3c.form.object, line 208, in updateWidgets
    Module z3c.form.object, line 87, in update
    Module plone.z3cform.patch, line 21, in BaseForm_update
    Module z3c.form.form, line 150, in update
    Module z3c.form.form, line 134, in updateWidgets
    Module z3c.form.field, line 243, in update
    Module z3c.form.datamanager, line 102, in canWrite
    Module z3c.form.datamanager, line 66, in adapted_context

     TypeError: ('Could not adapt', u'W', <InterfaceClass collective.cookiecuttr.interfaces.ITextRowSchema>)

**Comment by djowett** [comment]
Hi, I'm realising that every time I reinstall this product thru ZMI/portal_quickinstaller I get the error I mentioned above:

       ERROR plone.app.viewletmanager rendering of plone.htmlhead in collective.cookiecuttr fails: 'unicode' object has no attribute 'get'

Ok, I should be running the upgrade step ... but isn't this something that could work better?

**Comment by mauritsvanrees** [comment]
So this is with version 0.7.4?  Which Plone version?

When I use the buildout in this repository, I cannot reproduce it.

How would you trigger this?  Do you first install 0.7.1, set some settings, update the version to 0.7.4, then reinstall, then it gives an error?

And I wonder, do you also mean: after running the upgrade step it is fine, but if you then reinstall, it is broken again?

There *is* a test failure that looks related:

```
Error in test test_viewlet_is_not_installed (collective.cookiecuttr.tests.test_viewlet.CookieCuttrViewletTestCase)
Traceback (most recent call last):
  File "/Users/mauritsvanrees/shared-eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 403, in debug
    getattr(self, self._testMethodName)()
  File "/Users/mauritsvanrees/community/collective.cookiecuttr/src/collective/cookiecuttr/tests/test_viewlet.py", line 48, in test_viewlet_is_not_installed
    self.failUnlessEqual(len(my_viewlet), 0)
  File "/Users/mauritsvanrees/shared-eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 619, in deprecated_func
    return original_func(*args, **kwargs)
  File "/Users/mauritsvanrees/shared-eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 521, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/mauritsvanrees/shared-eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 514, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 0
```

But I do not trust this test. It claims to test that the viewlet is not there when the product is not installed, but in fact the product *is* installed. So the viewlet is there.

```
(Pdb) ICookieCuttr.providedBy(request)
True
(Pdb) pp [product for product in self.portal.portal_quickinstaller.listInstalledProducts() if product['title'] == u'collective.cookiecuttr']
[{'hasError': False,
  'id': 'collective.cookiecuttr',
  'installedVersion': '0.7.5.dev0',
  'isHidden': False,
  'isLocked': False,
  'status': 'installed',
  'title': u'collective.cookiecuttr'}]
```

But the viewlet is not available, so it will not render:

```
(Pdb) viewlet = my_viewlet[0]
(Pdb) viewlet
<Products.Five.viewlet.metaconfigure.CookieCuttrViewlet object at 0x10f4d97d0>
(Pdb) viewlet.available()
False
```

**Comment by djowett** [comment]
Hi @mauritsvanrees, thanks for investigating this.

To recreate this, I am re-installing my policy product through the quickeinstalller which has collective.cookiecuttr as a dependency in metadata.xml.   However I realise this DOESN'T happen if I re-install collective.cookiecuttr thru' the quickinstaller. 

However on reviewing this, I think this error *may* be due to these records in registry.xml in my policy product:

    <registry>

      <record name="collective.cookiecuttr.interfaces.ICookieCuttrSettings.cookiecuttr_enabled" interface="collective.cookiecuttr.interfaces.ICookieCuttrSettings" field="cookiecuttr_enabled">
        <field type="plone.registry.field.Bool">
          <default>False</default>
          <description>help_cookiecuttr_enable</description>
          <required>False</required>
          <title>Enable CookieCuttr</title>
        </field>
        <value>True</value>
      </record>

      <record name="collective.cookiecuttr.interfaces.ICookieCuttrSettings.text" interface="collective.cookiecuttr.interfaces.ICookieCuttrSettings" field="text">
        <field type="plone.registry.field.TextLine">
          <default>We use cookies. &lt;a href='{{cookiePolicyLink}}' title='read about our cookies'&gt;Read everything&lt;/a&gt;</default>
          <required>False</required>
          <title>Text to show your visitor</title>
        </field>
        <value>We use cookies on this website, you can &lt;a href='{{cookiePolicyLink}}' title='read our privacy statement'&gt;read about them here&lt;/a&gt;. To use the website as intended please...</value>
      </record>

      <record name="collective.cookiecuttr.interfaces.ICookieCuttrSettings.link" interface="collective.cookiecuttr.interfaces.ICookieCuttrSettings" field="link">
        <field type="plone.registry.field.TextLine">
          <required>False</required>
          <title>Link to page</title>
        </field>
        <value>service/privacy-statement#cookies</value>
      </record>

      <record name="collective.cookiecuttr.interfaces.ICookieCuttrSettings.accept_button" interface="collective.cookiecuttr.interfaces.ICookieCuttrSettings" field="accept_button">
        <field type="plone.registry.field.TextLine">
          <default>Accept cookies</default>
          <required>False</required>
          <title>Text to show in the Accept button</title>
        </field>
        <value>Accept cookies</value>
      </record>

    </registry>

I guess these registry records have changed since the integration of datagridfield?  I can't figure how to rework this file, any thoughts?

**Comment by mauritsvanrees** [comment]
I would say: install cookiecuttr in a fresh Plone Site, configure it as you want, go to portal_setup, export the configuration registry, and compare what you get.

**Comment by djowett** [comment]
@mauritsvanrees Thanks, I exported a registry and tried reimporting it....
but I an issue like this when trying to re-install with my registry.xml

http://stackoverflow.com/questions/17998903/using-collective-z3cform-datagridfield-with-plone-app-registry-and-genericsetup
(note the comment from Mikko on that question)

I think that's a separate issue though, so we could close this one?

**Comment by mauritsvanrees** [comment]
Sounds like a separate issue yes, in either datagridfield or plone.app.registry.

I'll close this one. Actually, no, I can't. :-) Someone of Four Digits will have to do that.

**Comment by djowett** [comment]
Sure, I think this should be closed. Thanks I will investigate & probably open a new issue for the other error.

I should say that the release introducing this interface change (for registry.xml) shouldn't IMHO have been a patch release (i.e. it should have been 0.8 instead of 0.7.2).
